// Gradle init.script for publisering til nexus

//    gradle publish --init-script config/gradle/scripts/mavenPublish.gradle

rootProject {
    if (name != 'buildSrc') {
        allprojects { Project project ->
            plugins.withType(MavenPublishPlugin) {
                project.publishing {
                    repositories {
                        String mavenUsr = System.getenv('DEPLOYUSER_USR')
                        String mavenPwd = System.getenv('DEPLOYUSER_PSW')
                        String mavenUpload = "https://nexus.statkart.no/repository/releases/"

                        maven {
                            url mavenUpload
                            credentials {
                                username mavenUsr
                                password mavenPwd
                            }
                        }
                    }
                }
            }
        }
    }
}
