// Gradle init.script for publisering til nexus
// Eksempel-bruk:
//      https://maven.pkg.github.com/kartverket/matrikkel-transform
//    set MAVEN_PUBLISH=https://username:password@nexus.statkart.no/repository/releases
//    gradle publish --init-script config/gradle/scripts/mavenPublish.gradle

rootProject {
    if (name != 'buildSrc') {
        allprojects { Project project ->
            plugins.withType(MavenPublishPlugin) {
                project.publishing {
                    repositories {
                        String mavenUsr = System.getenv('GITHUB_USER')
                        String mavenPwd = System.getenv('GITHUB_TOKEN')
                        String mavenUpload = "https://maven.pkg.github.com/kartverket/matrikkel-transform"

                        maven {
                                name "GitHubPackages"
                                url mavenUpload
                                credentials {
                                    username mavenUsr
                                    password mavenPwd
                                }
                        }
                    }
                }
            }
        }
    }
}
