plugins {
    id 'java-library'
    id 'maven-publish'
}

version = '1.2.0'
group = 'no.kartverket.matrikkel'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.slf4j:slf4j-api:1.7.30'

    testImplementation 'junit:junit:4.12'
    testImplementation 'org.assertj:assertj-core:3.14.0'
    testRuntimeOnly 'org.slf4j:slf4j-simple:1.8.0-beta4'
}

jar {
    into('lib') {
        from('lib')
    }
    into('transformation_init') {
        from('transformation_init')
    }
}

test {
    classpath += files(jar)
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/kartverket/matrikkel-transform")
            credentials {
                username = project.findProperty("USERNAME") ?: System.getenv("USERNAME")
                password = project.findProperty("TOKEN") ?: System.getenv("TOKEN")
            }
        }
    }
    publications {
        transform(MavenPublication) {
            from components.java
        }
    }

    if (project.hasProperty("deployUser") && project.hasProperty("deployPassword")) {
        repositories {
            maven {
                url = "https://nexus.statkart.no/repository/releases/"
                credentials {
                    username = "$deployUser"
                    password = "$deployPassword"
                }
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
