# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: Component
metadata:
  name: "matrikkel-transform"
  description: "Transformasjons bibliotek for koordinater som brukes i matrikkelen."
  tags:
    - "public"
spec:
  type: library
  lifecycle: production
  owner: heimdall
  system: matrikkel
