def baseVersion = "1.4.7"

pipeline {

    agent {
        node {
            label 'docker-builder-stor'
        }
    }


    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10'))
        disableConcurrentBuilds()
    }

    stages {
        stage('NotifyStarted') {
            steps {
                sendNotifications('STARTED', 'gb-docker')
            }
        }

        stage('Checkout skt2lan2') {
            steps {
                dir('skt2lan2') {
                    checkout(
                        [
                            $class: 'GitSCM',
                            branches: [[name: "master"]],
                            userRemoteConfigs: [
                                [
                                    credentialsId: '2c90ed8a-1f70-41f3-92e9-ce54dbd353c7',
                                    url: 'ssh://git@bitbucket.statkart.no:7999/mat/skt2lan2.git'
                                ]
                            ]
                        ]
                    )
                }
            }
        }

        stage('Build') {
            steps {
                withDockerContainer("nexus.statkart.no:8083/gfortran-builder:latest") {
                    dir("skt2lan2/src") {
                        sh "make -f Makefile.static"
                        sh "install -m 644 libskt2lan2.a ../../native"
                    }
                    dir("native") {
                        sh "make"
                        sh "mkdir dist"
                        sh "tar cJvf transform-native-linux-`uname -m`-${BUILD_NUMBER}.tar.xz libsositrans.so libskt2lan2.a"
                        sh "mv transform-native-linux-`uname -m`-${BUILD_NUMBER}.tar.xz dist"
                    }
                }
            }
        }

        stage('Publish') {
            steps {
                cifsPublisher(
                    alwaysPublishFromMaster: false,
                    continueOnError: false,
                    failOnError: true,
                    publishers: [[
                        configName: 'devbin',
                        transfers: [[
                            cleanRemote: false,
                            excludes: '',
                            flatten: false,
                            makeEmptyDirs: false,
                            noDefaultExcludes: false,
                            patternSeparator: '[, ]+',
                            remoteDirectory: 'transform',
                            remoteDirectorySDF: false,
                            removePrefix: "native/dist/",
                            sourceFiles: "native/dist/"
                        ]],
                        usePromotionTimestamp: false,
                        useWorkspaceInPromotion: false,
                        verbose: true
                    ]]
                )
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}
