@Library('common@master') _

pipeline {
    agent {
        node {
            label "matrikkel-utils"
        }
    }

    tools {
        jdk 'Java 11 Latest'
    }

    environment {
        gradleOptions = "--info " +
                "--refresh-dependencies " +
                "-Dmaven.repo.local=${WORKSPACE}/.m2/repository " +
                "-Dorg.gradle.daemon=false " +
                "-Pbuild_number=${BUILD_NUMBER} " +
                "-Djava.security.egd=file:///dev/urandom"
    }

    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: "20"))
        disableConcurrentBuilds()
    }

    stages {
        stage("Clean") {
            steps {
                sh "./gradlew ${gradleOptions} clean"
            }
        }

        stage("Build") {
            steps {
                sh "./gradlew ${gradleOptions} assemble"
            }
        }
        stage("Publish GitHub") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'matrikkel-pat-github',
                    usernameVariable: 'GITHUB_USER',
                    passwordVariable: 'GITHUB_TOKEN')
                ]) {
                        sh "./gradlew ${gradleOptions} publish -PprojectVersion=${TAG_NAME} --init-script gradle/scripts/mavenPublishGitHub.gradle"
                    }
                }
            }
//        stage("Publish Nexus") {
//            steps {
//                withCredentials([usernamePassword(
//                    credentialsId: 'nexusdeploy',
//                    usernameVariable: 'DEPLOYUSER_USR',
//                    passwordVariable: 'DEPLOYUSER_PSW')
//                ]) {
//                        sh "./gradlew ${gradleOptions} -Pversion=${TAG_NAME} publish --init-script gradle/scripts/mavenPublish.gradle "
//                }
//            }
//        }
    }

    post {
        always {
            deleteDir()
        }
    }
}
