@Library('common@master') _

pipeline {
    agent {
        node {
            label "matrikkel-utils"
        }
    }

    tools {
        jdk 'Java 12 Latest'
    }

    parameters {
        string(name: "tag", description: "Tag / versjon som skal publiseres (spesifiser kun tag her). Husk å sette versjon i build.gradle og tagge med samme versjon først!")
    }

    environment {
        DEPLOYUSER = credentials("nexusdeploy")
        deployOptions = "-PdeployUser=${DEPLOYUSER_USR} " +
                "-PdeployPassword=${DEPLOYUSER_PSW}"
        gradleOptions = "--info " +
                "--refresh-dependencies " +
                "-Dmaven.repo.local=${WORKSPACE}/.m2/repository " +
                "-Dorg.gradle.daemon=false " +
                "-Pbuild_number=${BUILD_NUMBER} " +
                "-Djava.security.egd=file:///dev/urandom"
    }

    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: "20"))
        disableConcurrentBuilds()
        skipDefaultCheckout()
    }

    stages {
        stage("Checkout") {
            steps {
                checkout([
                    $class: "GitSCM",
                    branches: [[name: "refs/tags/${params.tag}"]],
                    userRemoteConfigs: [[
                        credentialsId: 'Github-app-matrikkel',
                        url: "https://github.com/kartverket/matrikkel-transform.git"
                    ]]
                ])
            }
        }

        stage("Clean") {
            steps {
                sh "./gradlew ${gradleOptions} clean"
            }
        }

        stage("Build") {
            steps {
                sh "./gradlew ${gradleOptions} assemble"
            }
        }

        stage("Publish") {
            steps {
                withCredentials([
                        file(credentialsId: "kodesignering.p12", variable: "keystore"),
                        usernamePassword(
                                credentialsId: "kodesigneringp12",
                                passwordVariable: "keystore_password",
                                usernameVariable: "keystore_alias")]) {
                    sh "./gradlew ${gradleOptions} ${deployOptions} publish"
                }
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}
